// <auto-generated />
using System;
using GroupProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupProject.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240627005626_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GroupProject.Models.AnhSP", b =>
                {
                    b.Property<int>("MaAnhSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnhSP"), 1L, 1);

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<string>("TenFileAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaAnhSP");

                    b.HasIndex("MaSP");

                    b.ToTable("AnhSPs");
                });

            modelBuilder.Entity("GroupProject.Models.ChatLieu", b =>
                {
                    b.Property<int>("MaChatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChatLieu"), 1L, 1);

                    b.Property<string>("ChatLieuSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChatLieu");

                    b.ToTable("ChatLieus");
                });

            modelBuilder.Entity("GroupProject.Models.ChiTietHDB", b =>
                {
                    b.Property<int>("MaChiTietHDB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietHDB"), 1L, 1);

                    b.Property<double>("DonGiaBan")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiamGia")
                        .HasColumnType("float");

                    b.Property<int>("MaChiTietSP")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietHDB");

                    b.HasIndex("MaChiTietSP");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ChiTietHDBs");
                });

            modelBuilder.Entity("GroupProject.Models.ChiTietSanPham", b =>
                {
                    b.Property<int>("MaChiTietSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietSP"), 1L, 1);

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DonGiaBan")
                        .HasColumnType("float");

                    b.Property<double>("GiamGia")
                        .HasColumnType("float");

                    b.Property<int>("MaKichThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaMauSac")
                        .HasColumnType("int");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<int>("SLTon")
                        .HasColumnType("int");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChiTietSP");

                    b.HasIndex("MaKichThuoc");

                    b.HasIndex("MaMauSac");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietSanPhams");
                });

            modelBuilder.Entity("GroupProject.Models.DanhMucSP", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"), 1L, 1);

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CanNang")
                        .HasColumnType("float");

                    b.Property<double>("ChietKhau")
                        .HasColumnType("float");

                    b.Property<bool>("DoNoi")
                        .HasColumnType("bit");

                    b.Property<double>("GiaLonNhat")
                        .HasColumnType("float");

                    b.Property<double>("GiaNhoNhat")
                        .HasColumnType("float");

                    b.Property<string>("GioiThieuSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChatLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaDT")
                        .HasColumnType("int");

                    b.Property<string>("MaDacTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaHangSX")
                        .HasColumnType("int");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int>("MaNuocSX")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganLapTop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiGianBaoHanh")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSP");

                    b.HasIndex("MaChatLieu");

                    b.HasIndex("MaDT");

                    b.HasIndex("MaHangSX");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNuocSX");

                    b.ToTable("DanhMucSPs");
                });

            modelBuilder.Entity("GroupProject.Models.HangSX", b =>
                {
                    b.Property<int>("MaHangSX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHangSX"), 1L, 1);

                    b.Property<string>("HangSXSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNuocThuongHieu")
                        .HasColumnType("int");

                    b.HasKey("MaHangSX");

                    b.ToTable("HangSXs");
                });

            modelBuilder.Entity("GroupProject.Models.HoaDonBan", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiamGiaHD")
                        .HasColumnType("float");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaSoThue")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTinThue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TongTienHD")
                        .HasColumnType("float");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HoaDonBans");
                });

            modelBuilder.Entity("GroupProject.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"), 1L, 1);

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cusname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("Username");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("GroupProject.Models.KichThuoc", b =>
                {
                    b.Property<int>("MaKichThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKichThuoc"), 1L, 1);

                    b.Property<string>("KichThuocSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKichThuoc");

                    b.ToTable("KichThuocs");
                });

            modelBuilder.Entity("GroupProject.Models.LoaiDT", b =>
                {
                    b.Property<int>("MaDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDT"), 1L, 1);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDT");

                    b.ToTable("LoaiDTs");
                });

            modelBuilder.Entity("GroupProject.Models.LoaiSP", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"), 1L, 1);

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSPs");
                });

            modelBuilder.Entity("GroupProject.Models.MauSac", b =>
                {
                    b.Property<int>("MaMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMauSac"), 1L, 1);

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMauSac");

                    b.ToTable("MauSacs");
                });

            modelBuilder.Entity("GroupProject.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"), 1L, 1);

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("Username");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("GroupProject.Models.QuocGia", b =>
                {
                    b.Property<int>("MaNuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNuoc"), 1L, 1);

                    b.Property<string>("TenNuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNuoc");

                    b.ToTable("QuocGias");
                });

            modelBuilder.Entity("GroupProject.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GroupProject.Models.AnhSP", b =>
                {
                    b.HasOne("GroupProject.Models.DanhMucSP", "DanhMucSP")
                        .WithMany("AnhSPs")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucSP");
                });

            modelBuilder.Entity("GroupProject.Models.ChiTietHDB", b =>
                {
                    b.HasOne("GroupProject.Models.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("ChiTietHDBs")
                        .HasForeignKey("MaChiTietSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupProject.Models.HoaDonBan", "HoaDonBan")
                        .WithMany("ChiTietHDBs")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("HoaDonBan");
                });

            modelBuilder.Entity("GroupProject.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("GroupProject.Models.KichThuoc", "KichThuoc")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaKichThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupProject.Models.MauSac", "MauSac")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupProject.Models.DanhMucSP", "DanhMucSP")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucSP");

                    b.Navigation("KichThuoc");

                    b.Navigation("MauSac");
                });

            modelBuilder.Entity("GroupProject.Models.DanhMucSP", b =>
                {
                    b.HasOne("GroupProject.Models.ChatLieu", "ChatLieu")
                        .WithMany("DanhMucSPs")
                        .HasForeignKey("MaChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupProject.Models.LoaiDT", "LoaiDT")
                        .WithMany("DanhMucSPs")
                        .HasForeignKey("MaDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupProject.Models.HangSX", "HangSX")
                        .WithMany("DanhMucSPs")
                        .HasForeignKey("MaHangSX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupProject.Models.LoaiSP", "LoaiSP")
                        .WithMany("DanhMucSPs")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupProject.Models.QuocGia", "QuocGia")
                        .WithMany("DanhMucSPs")
                        .HasForeignKey("MaNuocSX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("HangSX");

                    b.Navigation("LoaiDT");

                    b.Navigation("LoaiSP");

                    b.Navigation("QuocGia");
                });

            modelBuilder.Entity("GroupProject.Models.HoaDonBan", b =>
                {
                    b.HasOne("GroupProject.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDonBans")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupProject.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDonBans")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("GroupProject.Models.KhachHang", b =>
                {
                    b.HasOne("GroupProject.Models.User", null)
                        .WithMany("KhachHang")
                        .HasForeignKey("Username");
                });

            modelBuilder.Entity("GroupProject.Models.NhanVien", b =>
                {
                    b.HasOne("GroupProject.Models.User", null)
                        .WithMany("NhanVien")
                        .HasForeignKey("Username");
                });

            modelBuilder.Entity("GroupProject.Models.ChatLieu", b =>
                {
                    b.Navigation("DanhMucSPs");
                });

            modelBuilder.Entity("GroupProject.Models.ChiTietSanPham", b =>
                {
                    b.Navigation("ChiTietHDBs");
                });

            modelBuilder.Entity("GroupProject.Models.DanhMucSP", b =>
                {
                    b.Navigation("AnhSPs");

                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("GroupProject.Models.HangSX", b =>
                {
                    b.Navigation("DanhMucSPs");
                });

            modelBuilder.Entity("GroupProject.Models.HoaDonBan", b =>
                {
                    b.Navigation("ChiTietHDBs");
                });

            modelBuilder.Entity("GroupProject.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDonBans");
                });

            modelBuilder.Entity("GroupProject.Models.KichThuoc", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("GroupProject.Models.LoaiDT", b =>
                {
                    b.Navigation("DanhMucSPs");
                });

            modelBuilder.Entity("GroupProject.Models.LoaiSP", b =>
                {
                    b.Navigation("DanhMucSPs");
                });

            modelBuilder.Entity("GroupProject.Models.MauSac", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("GroupProject.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDonBans");
                });

            modelBuilder.Entity("GroupProject.Models.QuocGia", b =>
                {
                    b.Navigation("DanhMucSPs");
                });

            modelBuilder.Entity("GroupProject.Models.User", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
